letisko-web/src/main/java/letisko/ui/DestinaceBean.java
package letisko.ui;

import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJBTransactionRolledbackException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import letisko.api.CommonTO;
import letisko.api.DestinaceTO;
import letisko.exception.EntityNotAvailableException;
import letisko.service.LetiskoGenericService;

/**
 * User: akovari Date: 10/19/13 Time: 7:32 PM
 */
@Named("destinace")
@RequestScoped
public class DestinaceBean {

    @Inject
    private LetiskoGenericService letisko;
    private DestinaceTO destinaceTO;

    @PostConstruct
    public void init() {
        destinaceTO = new DestinaceTO();
    }

    public LetiskoGenericService getLetisko() {
        return letisko;
    }

    public void setLetisko(LetiskoGenericService letisko) {
        this.letisko = letisko;
    }

    public DestinaceTO getDestinaceTO() {
        return destinaceTO;
    }

    public void setDestinaceTO(DestinaceTO destinaceTO) {
        this.destinaceTO = destinaceTO;
    }

    public List<DestinaceTO> getVsetkyDestinace() {
        return letisko.vsetky(DestinaceTO.class);
    }

    public String uloz() {
        try {
            if (letisko.nacitaj(DestinaceTO.class, destinaceTO.getId()) == null) {
                destinaceTO.setId(null);
                letisko.vytvor(destinaceTO);
            } else {
                letisko.uprav(destinaceTO);
            }
        } catch (EntityNotAvailableException ex) {
            Logger.getLogger(DestinaceBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return "destinace_list";
    }

    public void zmaz(Class<? extends CommonTO> type, Long id) {
        try {
            letisko.zmaz(type, id);
        } catch (EJBTransactionRolledbackException e) {
            FacesContext context = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ResourceBundle.getBundle(context.getApplication().getMessageBundle(), context.getViewRoot().getLocale());
            context.addMessage("zmaz", new FacesMessage(bundle.getString("EJBTransactionRolledbackException")));
        }
    }
}

letisko-web/src/main/java/letisko/ui/LetBean.java
package letisko.ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.TimeZone;

import javax.annotation.PostConstruct;
import javax.ejb.EJBTransactionRolledbackException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import letisko.api.CommonTO;
import letisko.api.DestinaceTO;
import letisko.api.LetTO;
import letisko.api.LetadloTO;
import letisko.api.LetuskaTO;
import letisko.exception.EntityNotAvailableException;
import letisko.service.LetiskoGenericService;

/**
 *
 * @author Martin Pitonak <mpitonak@mail.muni.cz>
 */
@Named("let")
@RequestScoped
public class LetBean {
    @Inject
    private LetiskoGenericService letisko;
    private LetTO letTO;

    private Long selectedOdkud;
    private Long selectedKam;
    private Long selectedLetadlo;
    private String selectedOdlet;
    private String selectedPrilet;
    private List<Long> selectedLetusky;

    @PostConstruct
    public void init() {
        letTO = new LetTO();
    }

    public LetiskoGenericService getLetisko() {
        return letisko;
    }

    public void setLetisko(LetiskoGenericService letisko) {
        this.letisko = letisko;
    }

    public LetTO getLetTO() {
        return letTO;
    }

    public void setLetTO(LetTO letTO) {
        this.letTO = letTO;
        selectedKam = letTO.getDestinaceCil().getId();
        selectedOdkud = letTO.getDestinaceStart().getId();
        selectedLetadlo = letTO.getLetadlo().getId();
        selectedLetusky = new ArrayList<>(letTO.getLetusky().size());
        for (LetuskaTO letuska : letTO.getLetusky()) {
            selectedLetusky.add(letuska.getId());
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
        sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
        selectedOdlet = sdf.format(letTO.getOdlet());
        selectedPrilet = sdf.format(letTO.getPrilet());
    }

    public Long getSelectedOdkud() {
        return selectedOdkud;
    }

    public void setSelectedOdkud(Long selectedOdkud) {
        this.selectedOdkud = selectedOdkud;
    }

    public Long getSelectedKam() {
        return selectedKam;
    }

    public void setSelectedKam(Long selectedKam) {
        this.selectedKam = selectedKam;
    }

    public String getSelectedOdlet() {
        return selectedOdlet;
    }

    public void setSelectedOdlet(String selectedOdlet) {
        this.selectedOdlet = selectedOdlet;
    }

    public String getSelectedPrilet() {
        return selectedPrilet;
    }

    public void setSelectedPrilet(String selectedPrilet) {
        this.selectedPrilet = selectedPrilet;
    }

    public List<Long> getSelectedLetusky() {
        return selectedLetusky;
    }

    public void setSelectedLetusky(List<Long> selectedLetusky) {
        this.selectedLetusky = selectedLetusky;
    }

    public Long getSelectedLetadlo() {
        return selectedLetadlo;
    }

    public void setSelectedLetadlo(Long selectedLetadlo) {
        this.selectedLetadlo = selectedLetadlo;
    }

    public List<LetTO> getVsetkyLety() {
        return letisko.vsetky(LetTO.class);
    }

    public List<LetuskaTO> getVsetkyLetusky() {
        return letisko.vsetky(LetuskaTO.class);
    }

    public List<LetadloTO> getVsetkyLetadla() {
        return letisko.vsetky(LetadloTO.class);
    }

    public List<DestinaceTO> getVsetkyDestinace() {
        return letisko.vsetky(DestinaceTO.class);
    }

    public String uloz() {
        try {
            if (selectedOdkud == selectedKam) {
                throw new ParseException("diffdest", 0);
            }
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            sdf.setTimeZone(TimeZone.getTimeZone("UTC"));
            Date tempOdlet = sdf.parse(selectedOdlet);
            Date tempPrilet = sdf.parse(selectedPrilet);
            if (tempOdlet.after(tempPrilet)){
                throw new ParseException("reversedDates", 0);
            }
            letTO.setOdlet(tempOdlet);
            letTO.setPrilet(tempPrilet);
            List<LetuskaTO> letusky = new ArrayList<>();
            for (Long letuska : selectedLetusky) {
                letusky.add((LetuskaTO) letisko.nacitaj(LetuskaTO.class, letuska));
            }
            letTO.setLetusky(letusky);
            letTO.setDestinaceCil((DestinaceTO) letisko.nacitaj(DestinaceTO.class, selectedKam));
            letTO.setDestinaceStart((DestinaceTO) letisko.nacitaj(DestinaceTO.class, selectedOdkud));
            letTO.setLetadlo((LetadloTO) letisko.nacitaj(LetadloTO.class, selectedLetadlo));

            if (letisko.nacitaj(LetTO.class, letTO.getId()) == null) {
                letTO.setId(null);
                letisko.vytvor(letTO);
            } else {
                letisko.uprav(letTO);
            }
        } catch (ParseException | EntityNotAvailableException ex) {
            FacesContext context = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ResourceBundle.getBundle(context.getApplication().getMessageBundle(), context.getViewRoot().getLocale());
            
            if (ex instanceof EntityNotAvailableException) context.addMessage("uloz", new FacesMessage(bundle.getString("EntityNotAvailableException")));
            else if (ex.getMessage().equals("diffdest")) context.addMessage("uloz", new FacesMessage(bundle.getString("NotDifferentDestinations")));
            else if (ex.getMessage().equals("reversedDates")) context.addMessage("uloz", new FacesMessage(bundle.getString("reversedDates")));
            
            return "let_edit";
        }
        return "let_list";
    }

    public void zmaz(Class<? extends CommonTO> type, Long id) {
        try{
            letisko.zmaz(type, id);
        }catch(EJBTransactionRolledbackException e){
            FacesContext context = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ResourceBundle.getBundle(context.getApplication().getMessageBundle(), context.getViewRoot().getLocale());
            context.addMessage("zmaz", new FacesMessage(bundle.getString("EJBTransactionRolledbackException")));
        }
    }

}

letisko-web/src/main/java/letisko/ui/LetadloBean.java
package letisko.ui;

import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJBTransactionRolledbackException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import letisko.api.CommonTO;
import letisko.api.LetadloTO;
import letisko.exception.EntityNotAvailableException;
import letisko.service.LetiskoGenericService;

/**
 * @author Martin Pitonak <mpitonak@mail.muni.cz>
 */
@Named("letadlo")
@RequestScoped
public class LetadloBean {

    @Inject
    private LetiskoGenericService letisko;
    private LetadloTO letadloTO;

    @PostConstruct
    public void init() {
        letadloTO = new LetadloTO();
    }

    public LetiskoGenericService getLetisko() {
        return letisko;
    }

    public void setLetisko(LetiskoGenericService letisko) {
        this.letisko = letisko;
    }

    public LetadloTO getLetadloTO() {
        return letadloTO;
    }

    public void setLetadloTO(LetadloTO letadloTO) {
        this.letadloTO = letadloTO;
    }

    public List<LetadloTO> getVsetkyLetadla() {
        return letisko.vsetky(LetadloTO.class);
    }

    public String uloz() {
        try {
            if (letisko.nacitaj(LetadloTO.class, letadloTO.getId()) == null) {
                letadloTO.setId(null);
                letisko.vytvor(letadloTO);
            } else {
                letisko.uprav(letadloTO);
            }
        } catch (EntityNotAvailableException ex) {
            Logger.getLogger(LetadloBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return "letadlo_list";
    }

    public void zmaz(Class<? extends CommonTO> type, Long id) {
        try {
            letisko.zmaz(type, id);
        } catch (EJBTransactionRolledbackException e) {
            FacesContext context = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ResourceBundle.getBundle(context.getApplication().getMessageBundle(), context.getViewRoot().getLocale());
            context.addMessage("zmaz", new FacesMessage(bundle.getString("EJBTransactionRolledbackException")));
        }
    }
}

letisko-web/src/main/java/letisko/ui/LetuskaBean.java
package letisko.ui;

import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJBTransactionRolledbackException;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import letisko.api.CommonTO;
import letisko.api.LetuskaTO;
import letisko.exception.EntityNotAvailableException;
import letisko.service.LetiskoGenericService;

@Named("letuska")
@RequestScoped
public class LetuskaBean {

    @Inject
    private LetiskoGenericService letisko;
    private LetuskaTO letuskaTO;

    @PostConstruct
    public void init() {
        letuskaTO = new LetuskaTO();
    }

    public LetiskoGenericService getLetisko() {
        return letisko;
    }

    public void setLetisko(LetiskoGenericService letisko) {
        this.letisko = letisko;
    }

    public LetuskaTO getLetuskaTO() {
        return letuskaTO;
    }

    public void setLetuskaTO(LetuskaTO letuskaTO) {
        this.letuskaTO = letuskaTO;
    }

    public List<LetuskaTO> getVsetkyLetusky() {
        return letisko.vsetky(LetuskaTO.class);
    }

    public String uloz() {
        try {
            if (letisko.nacitaj(LetuskaTO.class, letuskaTO.getId()) == null) {
                letuskaTO.setId(null);
                letisko.vytvor(letuskaTO);
            } else {
                letisko.uprav(letuskaTO);
            }
        } catch (EntityNotAvailableException ex) {
            Logger.getLogger(LetuskaBean.class.getName()).log(Level.SEVERE, null, ex);
        }

        return "letuska_list";
    }

    public void zmaz(Class<? extends CommonTO> type, Long id) {
        try {
            letisko.zmaz(type, id);
        } catch (EJBTransactionRolledbackException e) {
            FacesContext context = FacesContext.getCurrentInstance();
            ResourceBundle bundle = ResourceBundle.getBundle(context.getApplication().getMessageBundle(), context.getViewRoot().getLocale());
            context.addMessage("zmaz", new FacesMessage(bundle.getString("EJBTransactionRolledbackException")));
        }
    }
}

letisko-web/src/main/java/letisko/ui/SecurityBean.java
package letisko.ui;

import java.io.IOException;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;

@Named("security")
@RequestScoped
public class SecurityBean {

    public void login() {
        try {
            FacesContext.getCurrentInstance().getExternalContext().redirect(
                    FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath()
                            + "/secured_homepage.jsp");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public String logout() {
        ((HttpSession) FacesContext.getCurrentInstance().getExternalContext()
                .getSession(true)).invalidate();

        return "home";
    }
}

letisko-web/src/main/webapp/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" >
<head>
<title>Login failed</title>
</head>
<body>

    <ui:define name="title">
        ${msg.login_failed}
    </ui:define>

    <ui:composition template="template.xhtml">

        <ui:define name="box">

            <ul class="error-message">
                <li>${msg.login_error}</li>
            </ul>

        </ui:define>

    </ui:composition>

</body>
</html>

letisko-web/src/main/webapp/homepage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core">
    <head>
        <title>List</title>
    </head>
    <body>

        <ui:define name="title">
            ${msg.letisko}
        </ui:define>

        <ui:composition template="template.xhtml">
            <ui:define name="box">

                <div class="clearfix"></div>

                <div class="table-flights-name">

                    <h1 class="clear-form-name">${msg.lety}</h1>

                    <h:form styleClass="clear-form">
                        <h:commandLink action="let_add" styleClass="plus" rendered="#{request.isUserInRole('admins')}" />
                    </h:form>

                </div>

                <div id="table-header-detail">

                    <h:form>

                        <h:dataTable value="#{let.vsetkyLety}" var="l" styleClass="table-flights">

                            <div id="table-header">
                                <h:column>
                                    <f:facet name="header">${msg.datum}</f:facet>
                                    <h:outputText value="#{l.odlet}">
                                        <f:convertDateTime pattern="dd.MM.yyyy" />
                                    </h:outputText>
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.odkud}</f:facet>
                                        #{l.destinaceStart.mesto}
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.kam}</f:facet>
                                        #{l.destinaceCil.mesto}
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.cas_vzletu}</f:facet>
                                    <h:outputText value="#{l.odlet}">
                                        <f:convertDateTime pattern="HH:mm" />
                                    </h:outputText>
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.cas_pristani}</f:facet>
                                    <h:outputText value="#{l.prilet}">
                                        <f:convertDateTime pattern="HH:mm" />
                                    </h:outputText>
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.letadlo}</f:facet>
                                        #{l.letadlo.nazov}
                                </h:column>

                                <h:column>
                                    <f:facet name="header">${msg.letusky}</f:facet>
                                    <ui:repeat value="#{l.letusky}" var="item" varStatus="status">
                                        #{item.priezvisko}#{status.last ? '' : ','}
                                    </ui:repeat>
                                </h:column>

                                <h:column>
                                    <h:commandLink id="edit" action="let_edit" styleClass="edit" rendered="#{request.isUserInRole('admins')}">
                                        <f:setPropertyActionListener value="#{l}" target="#{let.letTO}" />
                                    </h:commandLink>
                                </h:column>

                                <h:column>
                                    <h:commandLink action="#{let.zmaz(l.getClass(), l.id)}" styleClass="trash" rendered="#{request.isUserInRole('admins')}" />
                                </h:column>

                            </div>
                        </h:dataTable>

                    </h:form>

                </div>

                <div class="clearfix"></div>

                <h:panelGroup rendered="#{request.isUserInRole('users') || request.isUserInRole('admins')}">
                    <div class="tables-in-row">

                        <div class="section-planes left">

                            <div>
                                <h2 class="clear-form-name">${msg.letadla}</h2>
                                <h:form styleClass="clear-form">
                                    <h:commandLink action="letadlo_add" styleClass="plus" rendered="#{request.isUserInRole('admins')}" />
                                </h:form>
                            </div>

                            <h:form>
                                <h:dataTable value="#{letadlo.vsetkyLetadla}" var="l" styleClass="table-entity">
                                    <h:column>
                                        <f:facet name="header">${msg.nazov}</f:facet>
                                            #{l.nazov}
                                    </h:column>

                                    <h:column>
                                        <f:facet name="header">${msg.typ}</f:facet>
                                            #{l.typ}
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">${msg.kapacita}</f:facet>
                                            #{l.kapacita}
                                    </h:column>

                                    <h:column>
                                        <h:commandLink id="edit" action="letadlo_edit" styleClass="edit" rendered="#{request.isUserInRole('admins')}">
                                            <f:setPropertyActionListener value="#{l}" target="#{letadlo.letadloTO}" />
                                        </h:commandLink>
                                    </h:column>

                                    <h:column>
                                        <h:commandLink action="#{letadlo.zmaz(l.getClass(), l.id)}" styleClass="trash" rendered="#{request.isUserInRole('admins')}" />
                                    </h:column>
                                </h:dataTable>
                            </h:form>

                        </div>

                        <div id="section-destinations" class="right">
                            <div>
                                <h2 class="clear-form-name">${msg.destinace}</h2>
                                <h:form styleClass="clear-form">
                                    <h:commandLink action="destinace_add" styleClass="plus" rendered="#{request.isUserInRole('admins')}" />
                                </h:form>
                            </div>

                            <h:form>
                                <h:dataTable value="#{destinace.vsetkyDestinace}" var="d" styleClass="table-entity">
                                    <h:column>
                                        <f:facet name="header">${msg.stat}</f:facet>
                                            #{d.stat}
                                    </h:column>

                                    <h:column>
                                        <f:facet name="header">${msg.mesto}</f:facet>
                                            #{d.mesto}
                                    </h:column>

                                    <h:column>
                                        <f:facet name="header"></f:facet> 
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header"></f:facet> 
                                    </h:column>

                                    <h:column>
                                        <h:commandLink id="edit" action="destinace_edit" styleClass="edit" rendered="#{request.isUserInRole('admins')}">
                                            <f:setPropertyActionListener value="#{d}" target="#{destinace.destinaceTO}" />
                                        </h:commandLink>
                                    </h:column>

                                    <h:column>
                                        <h:commandLink action="#{destinace.zmaz(d.getClass(), d.id)}" styleClass="trash" rendered="#{request.isUserInRole('admins')}" />
                                    </h:column>
                                </h:dataTable>
                            </h:form>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="tables-in-row">

                        <div class="section-planes left">
                            <div>
                                <h2 class="clear-form-name">${msg.letusky}</h2>
                                <h:form styleClass="clear-form">
                                    <h:commandLink action="letuska_add" styleClass="plus" rendered="#{request.isUserInRole('admins')}" />
                                </h:form>
                            </div>

                            <h:form>
                                <h:dataTable value="#{letuska.vsetkyLetusky}" var="l" styleClass="table-entity">
                                    <h:column>
                                        <f:facet name="header">${msg.meno}</f:facet>
                                            #{l.meno}
                                    </h:column>

                                    <h:column>
                                        <f:facet name="header">${msg.priezvisko}</f:facet>
                                            #{l.priezvisko}
                                    </h:column>

                                    <h:column>
                                        <f:facet name="header"></f:facet> 
                                    </h:column>

                                    <h:column>
                                        <h:commandLink id="edit" action="letuska_edit" styleClass="edit" rendered="#{request.isUserInRole('admins')}">
                                            <f:setPropertyActionListener value="#{l}" target="#{letuska.letuskaTO}" />
                                        </h:commandLink>
                                    </h:column>

                                    <h:column>
                                        <h:commandLink action="#{letuska.zmaz(l.getClass(), l.id)}" styleClass="trash" rendered="#{request.isUserInRole('admins')}" />
                                    </h:column>
                                </h:dataTable>
                            </h:form>

                        </div>
                    </div>
                </h:panelGroup>
            </ui:define>

        </ui:composition>

    </body>
</html>

letisko-web/src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html">
    <head>
        <title>Login</title>
    </head>
    <body>

        <ui:define name="title">
            ${msg.login}
        </ui:define>

        <ui:composition template="template.xhtml">

            <ui:define name="box">

                <form name="loginForm" method="post" action="j_security_check">
                    
                    <div class="form-wrapper">
                        
                        <h1 class="heading-login">${msg.login}</h1>

                        <p id="login-info">
                            ${msg.info}
                        </p>

                        <div id="login-forms">
                            <p>
                                <span class="login-labels">${msg.username}</span> <br />
                                <input class="input-login" type="text" name="j_username" size="15" />
                            </p>

                            <p>
                                <span class="login-labels">${msg.password}</span> <br />
                                <input class="input-login" type="password" size="15" name="j_password" />
                            </p>

                            <p>
                                <input type="submit" value="${msg.login_button}" class="button-login" />
                            </p>
                        </div>
                    </div>
                </form>
            </ui:define>

        </ui:composition>

    </body>
</html>

letisko-web/src/main/webapp/secured_homepage.jsp
<%
    response.sendRedirect(request.getContextPath());
%>

letisko-web/src/main/webapp/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title><ui:insert name="title">Airport Manager</ui:insert></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <link href="#{request.contextPath}/css/stylesheet.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="#{request.contextPath}/img/favicon.png" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,300&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css' />
        <link href='http://fonts.googleapis.com/css?family=Nunito:700' rel='stylesheet' type='text/css' />

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
        <link rel="stylesheet" type="text/css" href="#{request.contextPath}/css/jquery-ui-timepicker-addon.css" />
        <script type="text/javascript" src="#{request.contextPath}/css/jquery-ui-timepicker-addon.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $(".datepicker").datetimepicker({
                    controlType: 'select',
                    timeFormat: 'HH:mm',
                    dateFormat: "dd.mm.yy"
                });
            });
        </script>
    </h:head>

    <h:body>
        <header id="topBar">
            <a href="/pa165" id="logotype"></a>

            <div id="topLogin" class="wrapper">
                <h:form>
                    <h:commandLink action="#{security.login()}" value="#{msg.login}" rendered="#{empty request.remoteUser}" styleClass="button-signin" />
                    <h:commandLink action="#{security.logout()}" value="#{request.remoteUser} - #{msg.logout}" rendered="#{not empty request.remoteUser}" styleClass="button-signout" />
                </h:form>
            </div>
        </header>

        <div id="content" class="wrapper">
            <h:messages styleClass="error-message" />
            <ui:insert name="box">Box Content Here</ui:insert>
        </div>

        <div class="clearfix"></div>

        <footer class="wrapper">
            <hr />
            <strong>${msg.footer}</strong>

            <ul id="authors">
                <li><a href="https://is.muni.cz/auth/osoba/359593">Adam Kövári</a></li>
                <li><a href="https://is.muni.cz/auth/osoba/martin.beleja">Martin Beleja</a></li>
                <li><a href="https://is.muni.cz/auth/osoba/mpitonak">Martin Pitoňák</a></li>
                <li><a href="https://is.muni.cz/auth/osoba/430620">Marián Čepa</a></li>
            </ul>
        </footer>
    </h:body>
</html>